before_deploy: "echo 'ready?'"
branches:
  only:
    - main
deploy:
  provider: firebase
  token: 1//0cWS0s5wM-b_NCgYIARAAGAwSNwF-L9IraCkKfr91cGvJvthndzlBVvE1v9keBZYQqRSW5kt2RjqWP5jGoCOnku8TfEj0ILzW27E
  project: "redi-207ac"
  before_script:
  - npm install -g firebase-tools
  after_success:
  - ./deploy-to-firebase.sh
  on:
    branch: main
