language: node_js
node_js:
  - "19"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: 1//0cWS0s5wM-b_NCgYIARAAGAwSNwF-L9IraCkKfr91cGvJvthndzlBVvE1v9keBZYQqRSW5kt2RjqWP5jGoCOnku8TfEj0ILzW27E
  project: redi-207ac

branches:
  only:
    - main  # Установите здесь вашу основную ветку GIT

notifications:
  email: false
