before_deploy: "echo 'ready?'"
branches:
  only:
    - main
deploy:
  provider: firebase
  token:
    secure: "1//01qDWoxlpokoLCgYIARAAGAESNwF-L9IrUMhAAn3vPpAuYlOZILSDkx6U4dUCOSZG0FlNJQxQH5D-WCFtrMiTcQF01m60tMGVgGM"
  on:
    branch: main
