language: node_js
node_js:
    - "7.0"

branches:
  only:
    - main
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --project redi-207ac --token 1//0cWS0s5wM-b_NCgYIARAAGAwSNwF-L9IraCkKfr91cGvJvthndzlBVvE1v9keBZYQqRSW5kt2RjqWP5jGoCOnku8TfEj0ILzW27E
  on:
    branch: main
